version: '3.9'
services:
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    environment:
      - ${MONGO_INITDB_ROOT_USERNAME}
      - ${MONGO_INITDB_ROOT_PASSWORD}
  db-client:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://michael:secret@db:27017/
    depends_on:
      - db